### ISSUE TITLE
didn't work in apk (android)

### ISSUE THREAD

**Issue by seonu7875** [imrohit007/Video-Recording-React-Native-Expo#1]
be ok in emulator and expo(qrCode)
but build apk and download app -> didn't work video recording

**Comment by imrohit007** [comment]
That's not the code issue. You have to add camera permission to your app.json. For more check out the official documentation [here](https://docs.expo.dev/guides/permissions/) . In your case, you have to add this: "permissions": ["CAMERA"], in the android section of app.json
